### ISSUE TITLE
Use ImageCropBundle in default shop theme

### ISSUE THREAD

**Issue by fabianbarth-esono** [chameleon-system/chameleon-shop-theme-bundle#16]
Image crops should be used in the default shop theme. We can't change everything at once, so the following is proposed:

* Change image hotspot background image field to "Image with crop", so it's possible to select/create the crop right there in the table editor.
* Create a preset for standard teaser. If there is a crop with that preset for an image, it is used in the teaser.

We cannot use the fallback of the ImageCropBundle when there is no crop because we use a centered version instead of a trimmed version. So we have to use a conditional statement in the templates for backward compatibility.

**Comment by esono-anja** [comment]
Several problems, some of them might only be difficulties in understanding how this works (which is still a hint for usability):
1. Remove the cropped image. The backend shows the full picture and says that there is no cutout selected.
![cutout1](https://user-images.githubusercontent.com/15125103/53561636-b5cbd380-3b4f-11e9-989b-b1d64af3be6c.png)

The frontend, however, still shows the cropped image, which is also shown in the backend when you open "edit cutout". 
![cutout2](https://user-images.githubusercontent.com/15125103/53561825-1e1ab500-3b50-11e9-8ba2-04eb180b3631.png)

=> It should show the full image because I removed the selected cutout.

2. I have done 2 cutouts. Now I reset the cutout (no cutout is selected). I go to edit the cutout. Now I would expect to see the two cutouts I have done before. Instead I see only the last one, which I can either change and save or select. Where is the other cutout?
![cutout3](https://user-images.githubusercontent.com/15125103/53562367-7b633600-3b51-11e9-82fc-de6bb3ce2daf.png)

3. I go to edit coutout. I select "Custom cutout: New". Now the "Standard-Teaser (z.B. in Produktlisten verwendet)" is displayed all of the sudden. Where does that come from now and why only when I want to create a user-defined cutout? Besides, it is not translated (neither is "Presenter mit Hotspots: Hintergrundbild). and, i see my cutout "Presenter 2", but where is the other cutout "Presenter 1"? Obviously, it was overwritten, because in the media manager there is only "Presenter 2". But that is not clear when creating the crops.
![cutout4](https://user-images.githubusercontent.com/15125103/53562730-72bf2f80-3b52-11e9-8b7e-552c9c591f76.png)

4. Can I create only 1 Standard teaser cutout? If i create 2, which one is used in the list?

5. Is it not possible to delete cutouts in the media manager?

**Comment by umulmrum** [comment]
@fabianbarth-esono Can you help?

**Comment by fabianbarth-esono** [comment]
> 1. Remove the cropped image. The backend shows the full picture and says that there is no cutout selected. 
> The frontend, however, still shows the cropped image, which is also shown in the backend when you open "edit cutout".
> => It should show the full image because I removed the selected cutout.

Agreed and fixed. If we use the crop selection field, we should not fallback to any crop in the template.
Fixed by https://github.com/chameleon-system/chameleon-shop/pull/51

> 1. I have done 2 cutouts. Now I reset the cutout (no cutout is selected). I go to edit the cutout. Now I would expect to see the two cutouts I have done before. Instead I see only the last one, which I can either change and save or select. Where is the other cutout?
> 2. I go to edit coutout. I select "Custom cutout: New". Now the "Standard-Teaser (z.B. in Produktlisten verwendet)" is displayed all of the sudden. Where does that come from now and why only when I want to create a user-defined cutout?

The image selection field is restricted to the image hotspot preset, so only that one is displayed. The custom cutout should not be there. This is fixed by https://github.com/chameleon-system/chameleon-base/pull/264

> Besides, it is not translated (neither is "Presenter mit Hotspots: Hintergrundbild). 

Translations fixed in:
https://github.com/chameleon-system/chameleon-base/pull/263
https://github.com/chameleon-system/chameleon-shop-theme-bundle/pull/24
https://github.com/chameleon-system/chameleon-shop/pull/50

> And, i see my cutout "Presenter 2", but where is the other cutout "Presenter 1"? Obviously, it was overwritten, because in the media manager there is only "Presenter 2". But that is not clear when creating the crops.

Not sure if I understand this correctly, but I guess this was due to the restriction of the image selection field as described above. I assume it is fixed.

> 3. Can I create only 1 Standard teaser cutout? If i create 2, which one is used in the list?

For each preset, it is only possible to create one cutout.

> 4. Is it not possible to delete cutouts in the media manager?

Added this in https://github.com/chameleon-system/chameleon-base/pull/262

**Comment by fabianbarth-esono** [comment]
@umulmrum Assigning this to you for review.

**Comment by esono-anja** [comment]
a) The "reset cutout" button doesn't work, nothing happens.
![reset](https://user-images.githubusercontent.com/15125103/54549453-5b819e00-49aa-11e9-88de-29e3d8c71629.png)

b) I don't quite understand how the cutouts are supposed to work. We should look at it together, either @fabianbarth-esono or @umulmrum
